# fly.toml app configuration file generated for mochicake-linebot on 2025-10-14T16:22:15+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mochicake-linebot'
primary_region = 'nrt'

[build]

[deploy]
  strategy = 'rolling'
  max_unavailable = 1.0

[env]
  GRAPHQL_HOST = '0.0.0.0'
  GRAPHQL_PORT = '8080'
  DD_APM_ENABLED = 'true'
  DD_APM_INSTRUMENTATION_ENABLED = 'true'
  DD_DOGSTATSD_NON_LOCAL_TRAFFIC = 'false'
  DD_ENV = 'prod'
  DD_LOGS_CONFIG_AUTO_MULTI_LINE_DETECTION = 'true'
  DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL = 'true'
  DD_LOGS_ENABLED = 'true'
  DD_LOGS_INJECTION = 'true'
  DD_PROCESS_CONFIG_PROCESS_COLLECTION_ENABLED = 'true'
  DD_PROFILING_ENABLED = 'auto'
  DD_RUNTIME_SECURITY_CONFIG_EBPFLESS_ENABLED = 'true'
  DD_RUNTIME_SECURITY_CONFIG_ENABLED = 'true'
  DD_RUNTIME_SECURITY_CONFIG_REMOTE_CONFIGURATION_ENABLED = 'true'
  DD_SBOM_CONTAINER_IMAGE_ENABLED = 'true'
  DD_SBOM_ENABLED = 'true'
  DD_SBOM_HOST_ENABLED = 'true'
  DD_SERVICE = 'mochicake-linebot'
  DD_SITE = 'datadoghq.com'
  DD_SYSTEM_PROBE_ENABLED = 'true'
  DD_TAGS = 'fly_app:mochicake-linebot'
  DD_TRACE_REPORT_HOSTNAME = 'true'
  DD_VERSION = '1.0.0'
  NODE_ENV = 'production'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1
  processes = ['app']

[[services]]
  protocol = 'udp'
  internal_port = 8125
  processes = ['app']

  [[services.ports]]
    port = 8125

[[services]]
  protocol = 'tcp'
  internal_port = 8126
  processes = ['app']

  [[services.ports]]
    port = 8126

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

# Persistent volume for sqlite DB
[[mounts]]
  source = "linedata"
  destination = "/data"
  initial_size = "1GB"
