# fly.toml app configuration file generated for mochicake-linebot on 2025-10-14T16:22:15+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mochicake-linebot'
primary_region = 'nrt'

[build]

[deploy]
  strategy = 'rolling'
  max_unavailable = 1.0

[env]
  GRAPHQL_HOST = '0.0.0.0'
  GRAPHQL_PORT = '8080'
  DD_SERVICE = 'mochicake-linebot'
  DD_TAGS = 'fly_app:mochicake-linebot'
  NODE_ENV = 'production'

[[services]]
  protocol = 'udp'
  internal_port = 8125
  processes = ['app']

  [[services.ports]]
    port = 8125

[[services]]
  protocol = 'tcp'
  internal_port = 8126
  processes = ['app']

  [[services.ports]]
    port = 8126

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

# Persistent volume for sqlite DB
[[mounts]]
  source = "linedata"
  destination = "/data"
  initial_size = "1GB"
