// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
import {LineBotState} from "./src"

interface Env {
	LineBotState: DurableObjectNamespace<LineBotState>
	LINE_CHANNEL_TOKEN: string
	LINE_CHANNEL_SECRET: string
	DEMO_ACTIVE: string
	CATALYST_JWK_URL: string
}

